homeassistant:
  name: Dari's Home Assistant
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 38
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include customize.yaml
  packages: !include_dir_named packages
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
cover: !include cover.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
timer: !include timer.yaml
light: !include light.yaml
camera: !include camera.yaml
plant: !include plant.yaml
scene: !include scene.yaml
input_boolean: !include boolean.yaml
input_text:
input_select:
input_number:
input_datetime: !include datetime.yaml
cloud: !include cloud.yaml
homekit: !include homekit.yaml
stream:
wake_on_lan:
system_health:
map:
ios:
mobile_app:
config:
conversation:
sun:
updater:
# zeroconf:
# person:

binary_sensor:
  - platform: workday
    country: IT

mqtt:
  broker: !secret mqtt_broker
  discovery: true
  discovery_prefix: homeassistant
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

alarm_control_panel:
  - platform: mqtt
    code: !secret allarm_code
    state_topic: "riscopanel/armstatus"
    command_topic: "riscopanel/armstatus/SET"
    payload_disarm: "disarmed"
    payload_arm_home: "partially"
    payload_arm_away: "armed"

lovelace:
  mode: yaml

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password:  !secret netatmo_password
climate:
  - platform: netatmo

speedtestdotnet:
  scan_interval:
    hours: 6
  monitored_conditions:
    - ping
    - download
    - upload

yeelight:
  devices:
    192.168.1.87:
      name: camera
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
      model: color2
    192.168.1.72:
      name: studio
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
      model: mono1

#sonoff:   # questo è un custom component è necessario il relativo file
#  username: !secret sonoff_username
#  password: !secret sonoff_password
#  scan_interval: 60
#  grace_period: 600
#  api_region: 'eu'

#tplink:
#  discovery: false
#  switch:
#    - host: 192.168.1.115

zwave:
    usb_path: /dev/ttyACM0

sonos:
  media_player:
    hosts:
      - 192.168.1.82 #sala
      - 192.168.1.182 #camera

media_player:
  - platform: lg_netcast
    host: 192.168.1.89
    access_token: 577887
  - platform: androidtv
    name: Fire TV
    host: 192.168.1.124

frontend:
  themes: !include_dir_merge_named themes

http:
  base_url: !secret dns_url
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
#  trusted_networks:
#    - 127.0.0.1
#    - 192.168.1.0/24
#    - 172.17.0.0/16 # Example Docker bridge
#    - 172.30.32.0/23 # Example Docker hassio
#  ip_ban_enabled: true
#  login_attempts_threshold: 5
#  api_password: !secret http_password

discovery:
  ignore:
    - yeelight
    - sonos
    - plex_mediaserver

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: IT
  devices:
    - device_id: !secret dyson_device_id # eg: Pure Cool Link device
      device_ip: 192.168.1.70

weather:
  - platform: darksky
    name: Meteo
    api_key: !secret darksky_apikey

tts:  # Text to speech
  - platform: google_translate
    language: 'it'

notify:
  - name: telefoni
    platform: group
    services:
      - service: ios_davides_iphone
      - service: ios_iphone_di_muriel
      - service: ios_ipad_di_muriel

device_tracker:
  - platform: unifi_direct
    host: !secret unifi_host
    username: !secret unifi_user
    password: !secret unifi_password

panel_iframe:

###################### History e Log ##############################
history:
  use_include_order: True
  include:
    domains:
      - light
      - switch
      - binary_sensor
    entities:
      - device_tracker.davides_iphone
      - device_tracker.iphone_di_muriel
      - media_player.lg_tv_remote
      - sensor.widom_ume304_energy_driven_switch_power
      - sensor.widom_ume304_energy_driven_switch_energy
      - sensor.neo_coolcam_power_plug_12a_power
      - sensor.neo_coolcam_power_plug_12a_power_2
      - sensor.neo_coolcam_power_plug_12a_power_8
      - sensor.neo_coolcam_power_plug_12a_power_10
      - sensor.neo_coolcam_power_plug_12a_power_11
      - sensor.consumototale
      - sensor.neo_coolcam_battery_powered_pir_sensor_luminance
      - sensor.fibaro_system_fgms001zw5_motion_sensor_luminance
      - sensor.netatmo_regenmesser_rain
      - sensor.processor_use
      - device_tracker.suocera
      - media_player.lg_tv_remote
      - alarm_control_panel.mqtt_alarm
  exclude:
    entities:
      - light.fibaro_system_fgd212_dimmer_2_level_2
      - light.fibaro_system_fgd212_dimmer_2_level
recorder:
  purge_keep_days: 3
  exclude:
    domains:
      - sensor
      - device_tracker
  include:
    domains:
      - light
      - switch
      - input_datetime
      - input_boolean
      - input_select
      - input_number
      - input_text
      - automation
#      - script
      - binary_sensor
      - timer
    entities:
      - sensor.widom_ume304_energy_driven_switch_power
      - sensor.widom_ume304_energy_driven_switch_energy
      - sensor.neo_coolcam_power_plug_12a_power
      - sensor.neo_coolcam_power_plug_12a_power_2
      - sensor.neo_coolcam_power_plug_12a_power_3
      - sensor.neo_coolcam_power_plug_12a_power_8
      - sensor.neo_coolcam_power_plug_12a_power_10
      - sensor.neo_coolcam_power_plug_12a_power_11
      - sensor.consumototale
      - sensor.netatmo_regenmesser_rain
      - sensor.netatmo_regenmesser_sum_rain_24
      - sensor.rainfall_today
      - sensor.netatmo_outdoor_temperature
      - sensor.dark_sky_forecast_daytime_high_temperature_0
      - sensor.neo_coolcam_battery_powered_pir_sensor_luminance
      - sensor.fibaro_system_fgms001zw5_motion_sensor_luminance
      - sensor.processor_use
      - device_tracker.davides_iphone
      - device_tracker.iphone_di_muriel
      - device_tracker.suocera
      - sensor.neo_coolcam_power_plug_12a_previous_reading_6
      - sensor.neo_coolcam_power_plug_12a_previous_reading_32
      - sensor.neo_coolcam_power_plug_12a_previous_reading_39
      - media_player.lg_tv_remote
      - alarm_control_panel.mqtt_alarm
logbook:
  include:
    domains:
      - switch
      - binary_sensor
      - light
      - automation
#      - script
    entities:
      - device_tracker.davides_iphone
      - device_tracker.iphone_di_muriel
      - device_tracker.suocera
