homeassistant:
  name: Dari's Home Assistant
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 29    # Impacts weather/sunrise data (altitude above sea level in meters)
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include customize.yaml
  packages: !include_dir_named packages

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password:  !secret netatmo_password

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
cover: !include cover.yaml
sensor: !include sensor.yaml
scene: !include scene.yaml
input_boolean: !include boolean.yaml
#homekit: !include homekit.yaml
cloud: !include cloud.yaml
wake_on_lan:

#tuya:
#  username: !secret TUYA_USERNAME
#  password: !secret TUYA_PASSWORD
#  country_code: !secret TUYA_COUNTRYCODE

sonoff:
  email: !secret sonoff_username
  password: !secret sonoff_password
  scan_interval: 60
  grace_period: 600
  apihost: 'eu-api.coolkit.cc'

light:
  - platform: yeelight
    devices:
      192.168.1.87:
        name: camera
        transition: 1000
        use_music_mode: False #(defaults to False)
        save_on_change: False #(defaults to True)
      192.168.1.72:
        name: studio
        transition: 1000
        use_music_mode: False #(defaults to False)
        save_on_change: False #(defaults to True)

switch:
  - platform: wake_on_lan
    name: WOL iMac
    mac_address: !secret wol_imac
  - platform: tplink
    host: 192.168.1.115
    name: christmas_light

zwave:
    usb_path: /dev/ttyACM0

media_player:
  - platform: sonos
    hosts:
    - 192.168.1.82 #sala
    - 192.168.1.66 #camera
  - platform: lg_netcast
    host: 192.168.1.89
    access_token: 577887
  - platform: firetv

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url: !secret dns_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24
    - 172.17.0.0/16 # Example Docker bridge
    - 172.30.32.0/23 # Example Docker hassio

updater:
discovery:
  ignore:
    - yeelight
    - sonos
    - plex_mediaserver
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  use_include_order: True
  include:
    domains:
      - light
      - switch
    entities:
      - media_player.lg_tv_remote
      - sensor.neo_coolcam_power_plug_12a_power
      - sensor.neo_coolcam_power_plug_12a_power_2
      - sensor.neo_coolcam_power_plug_12a_power_8
      - sensor.neo_coolcam_power_plug_12a_power_10
      - sensor.netatmo_regenmesser_rain
  exclude:
    entities:
      - light.fibaro_system_fgd212_dimmer_2_level_2
      - light.fibaro_system_fgd212_dimmer_2_level
recorder:
  purge_keep_days: 5
  exclude:
    domains:
      - sensor
  include:
    domains:
      - light
      - switch
      - input_datetime
    entities:
      - sensor.neo_coolcam_power_plug_12a_power
      - sensor.neo_coolcam_power_plug_12a_power_2
      - sensor.neo_coolcam_power_plug_12a_power_8
      - sensor.neo_coolcam_power_plug_12a_power_10
      - sensor.netatmo_regenmesser_rain
#logbook:
#  include:
#    domains:
#      - switch

map:
ios:
dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: IT
  devices:
    - device_id: !secret dyson_device_id # eg: Pure Cool Link device
      device_ip: 192.168.1.70

weather:
  - platform: yweather
    name: Meteo
    woeid: !secret yweather_woeid
sun:

# Text to speech
tts:
  platform: google
  language: 'it'

#mqtt:
#  broker: core-mosquitto
#  username: !secret mqtt_username
#  password: !secret mqtt_password

notify:
  - name: telefoni
    platform: group
    services:
      - service: ios_davides_iphone
      - service: ios_iphone_di_muriel
  - name: firetv
    platform: nfandroidtv
    host: 192.168.1.124
    position: top-right
    duration: 2

device_tracker:
panel_iframe:
