homeassistant:
  name: Dari's Home Assistant
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 38
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include customize.yaml
  packages: !include_dir_named packages
automation: !include automations.yaml
binary_sensor: !include binary.yaml
camera: !include camera.yaml
cloud: !include cloud.yaml
cover: !include cover.yaml
config:
conversation:
default_config:
ffmpeg:
group: !include groups.yaml
homekit: !include homekit.yaml
input_boolean: !include boolean.yaml
input_text:
input_select:
input_number: !include input_number.yaml
input_datetime: !include datetime.yaml
ios:
light: !include light.yaml
map:
mobile_app:
person:
pi_hole:
  host: !secret pihole_url
plant: !include plant.yaml
scene: !include scene.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
stream:
ssdp:
sun:
switch: !include switch.yaml
system_health:
timer: !include timer.yaml
updater:
wake_on_lan:
zeroconf:
zone: !include zones.yaml

lovelace:
  mode: yaml

alarm_control_panel:
  - platform: mqtt
    code: !secret allarm_code
    state_topic: "riscopanel/armstatus"
    command_topic: "riscopanel/armstatus/SET"
    payload_disarm: "disarmed"
    payload_arm_home: "partially"
    payload_arm_away: "armed"
lock:
  - platform: nuki
    host: !secret nuki_host
    token: !secret nuki_token

#netatmo:
#  api_key: !secret netatmo_api_key
#  secret_key: !secret netatmo_secret_key

speedtestdotnet:
  scan_interval:
    hours: 6
  monitored_conditions:
    - ping
    - download
    - upload

yeelight:
  devices:
    192.168.10.95:
      name: camera
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
      model: color2
    192.168.10.96:
      name: studio
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
      model: mono1
    192.168.10.97:
      name: sala
      transition: 1000
      use_music_mode: False #(defaults to False)
      save_on_change: False #(defaults to True)
      model: color2

zwave:
    usb_path: /dev/ttyACM0

sonos:
  media_player:
    hosts:
      - 192.168.10.51 #sala
      - 192.168.10.50 #camera

media_player:
  - platform: philips_android_tv
    name: philips_tv
    host: 192.168.10.59
    mac: !secret philips_mac
    username: !secret philips_user
    password: !secret philips_password

proxmoxve:
  - host: !secret proxmox_ip
    username: !secret proxmox_user
    password: !secret proxmox_pass
    verify_ssl: false
    nodes:
      - node: !secret proxmox_node
        vms:
          - 200
          - 254
        containers:
          - 101
          - 102
          - 103
          - 104
          - 105

frontend:
  themes: !include_dir_merge_named themes

http:
  base_url: !secret dns_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.10.104
  ip_ban_enabled: true
  login_attempts_threshold: 5

discovery:
  ignore:
    - yeelight
    - sonos
    - plex_mediaserver
    - homekit

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: IT
  devices:
    - device_id: !secret dyson_device_id # eg: Pure Cool Link device
      device_ip: 192.168.10.70

weather:
  - platform: darksky
    name: Meteo
    api_key: !secret darksky_apikey

tts:  # Text to speech
  - platform: google_translate
    language: 'it'

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_id_davide
      - !secret telegram_id_muriel

notify:
  - name: telefoni
    platform: group
    services:
      - service: ios_davides_iphone
      - service: ios_iphone_di_muriel
      - service: ios_ipad_di_muriel
  - name: davide
    platform: telegram
    chat_id: !secret telegram_id_davide
  - name: muriel
    platform: telegram
    chat_id: !secret telegram_id_muriel
  - name: telegram_all
    platform: group
    services:
      - service: davide
      - service: muriel
  - name: lametric
    platform: lametric
    lifetime: 20
    icon: a7956
    cycle: 1
  - name: tv
    platform: nfandroidtv
    host: 192.168.10.59
#custom component alexa
  - platform: alexa_media
    name: alexa_media

lametric:
  client_id: !secret lametric_id
  client_secret: !secret lametric_secret

device_tracker:
  - platform: unifi_direct
    host: !secret unifi_host
    username: !secret unifi_user
    password: !secret unifi_password

panel_iframe:

###################################################################
###################### HISTORY e LOG ##############################
###################################################################
recorder:
  purge_keep_days: 5
  exclude:
    domains:
      - sensor
      - device_tracker
  include:
    domains:
      - person
      - light
      - switch
      - cover
      - input_datetime
      - input_boolean
      - input_select
      - input_number
      - input_text
      - automation
      - lock
#      - script
      - binary_sensor
      - timer
      - alarm_control_panel
      - zwave
    entities:
      - fan.sala
      - sensor.asciugatrice_energy_power
      - sensor.lavatrice_energy_power
      - sensor.consumo_presa_bagno
      - sensor.consumo_presa_pranzo
      - sensor.consumo_presa_ingresso
      - sensor.consumo_presa_corridoio
      - sensor.consumo_ups_sottoscala
      - sensor.widom_ume304_energy_driven_switch_power
      - sensor.widom_ume304_energy_driven_switch_energy
      - sensor.neo_coolcam_power_plug_12a_power
      - sensor.neo_coolcam_power_plug_12a_power_2
      - sensor.neo_coolcam_power_plug_12a_power_3
      - sensor.neo_coolcam_power_plug_12a_power_8
      - sensor.neo_coolcam_power_plug_12a_power_10
      - sensor.neo_coolcam_power_plug_12a_power_11
      - sensor.consumototale
      - sensor.netatmo_regenmesser_rain
      - sensor.netatmo_regenmesser_sum_rain_24
      - sensor.rainfall_today
      - sensor.netatmo_outdoor_temperature
      - sensor.dark_sky_forecast_daytime_high_temperature_0
      - sensor.neo_coolcam_battery_powered_pir_sensor_luminance
      - sensor.fibaro_system_fgms001zw5_motion_sensor_luminance
      - sensor.processor_use
      - device_tracker.davides_iphone
      - device_tracker.iphone_di_muriel
      - device_tracker.suocera
      - sensor.neo_coolcam_power_plug_12a_previous_reading_6
      - sensor.neo_coolcam_power_plug_12a_previous_reading_32
      - sensor.neo_coolcam_power_plug_12a_previous_reading_39
      - media_player.philips_tv
      - alarm_control_panel.mqtt_alarm
      - sensor.hastudio_broadlink_sensor_temperature
      - sensor.memory_use_percent
      - sensor.fibaro_system_fgms001zw5_motion_sensor_temperature
      - sensor.consumi_generali_filtered
      - sensor.consumi_kwh_filtered
      - sensor.ore_alla_tv_oggi
      - sensor.ore_alla_tv_settimana

history:
  use_include_order: True
  include:
    domains:
      - light
      - switch
      - binary_sensor
      - person
      - alarm_control_panel
      - lock
    entities:
      - device_tracker.davides_iphone
      - device_tracker.iphone_di_muriel
      - media_player.philips_tv
      - sensor.widom_ume304_energy_driven_switch_power
      - sensor.widom_ume304_energy_driven_switch_energy
      - sensor.asciugatrice_energy_power
      - sensor.lavatrice_energy_power
      - sensor.neo_coolcam_power_plug_12a_power
      - sensor.neo_coolcam_power_plug_12a_power_2
      - sensor.neo_coolcam_power_plug_12a_power_8
      - sensor.neo_coolcam_power_plug_12a_power_10
      - sensor.neo_coolcam_power_plug_12a_power_11
      - sensor.consumototale
      - sensor.neo_coolcam_battery_powered_pir_sensor_luminance
      - sensor.fibaro_system_fgms001zw5_motion_sensor_luminance
      - sensor.netatmo_regenmesser_rain
      - sensor.processor_use
      - device_tracker.suocera
      - media_player.lg_tv_remote
      - alarm_control_panel.mqtt_alarm
  exclude:
    entities:
      - light.fibaro_system_fgd212_dimmer_2_level_2
      - light.fibaro_system_fgd212_dimmer_2_level
logbook:
  include:
    domains:
      - switch
      - binary_sensor
      - light
      - automation
      - person
      - lock
      - alarm_control_panel
#      - script
    entities:
      - device_tracker.suocera

########################################################
#####             CUSTOM COMPONENTS                #####
########################################################
# abilita lo store di componenti
hacs:
  token: !secret hacs_token
#componente custom per comandare un homeassistant remoto
remote_homeassistant:
  instances:
  - host: !secret remote_homeassistant_studio
    port: !secret remote_homeassistant_port
    secure: false
    access_token: !secret access_token_studio
    entity_prefix: "hastudio_"
#    include:
#      domains:
#        - sensor
#        - switch
#        - binary_sensor
#        - light

# componente non ufficiale per Alexa
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.it
