
resources:
  - url: /local/slider-entity-row.js
    type: js


title: Dari's Home Assistant


views:
  - title: default_view  #pagina
    icon: mdi:home
    badges:
      - device_tracker.davides_iphone
      - device_tracker.iphone_di_muriel
      #- switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch
    cards:               # card della pagina
      - type: horizontal-stack
        cards:
        - type: entity-button
          tap_action:
            action: toggle
          name: CANCELLO
          entity: switch.switch
        - type: entity-button
          tap_action:
            action: toggle
          name: PEDONALE
          entity: switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch
        - type: entity-button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.spengitv
          entity: script.spengitv
          name: TV OFF
          icon: mdi:power

      - type: entities
        title: Luci
        show_header_toggle: true
        entities:
          - type: section
            label: Piano Terra
          - switch.switch_9
          - switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_2
          - switch.switch_8
          - switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_3
          - switch.switch_15
          - type: divider
#          - switch.christmas_light
          - switch.switch_14
          - switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_4
          - type: section
            label: Piano Primo
          - type: custom:slider-entity-row
            entity: light.level
          - type: custom:slider-entity-row
            entity: light.level_2
          - type: custom:slider-entity-row
            entity: light.camera
          - type: custom:slider-entity-row
            entity: light.studio


      - type: entities
        title: Confort Living
        show_header_toggle: false
        entities:
          - climate.termostatod
          - fan.sala
          - type: divider
          - sensor.netatmo_indoor_temperature
          - sensor.netatmo_indoor_humidity
          - sensor.sala_humidity
          - sensor.netatmo_indoor_pressure
          - sensor.sala_aqi
          - sensor.netatmo_indoor_co2
          - sensor.sala_dust
          - sensor.netatmo_indoor_noise
      - type: entities
        title: Giardino
        show_header_toggle: false
        entities:
          - sun.sun
          - sensor.fasilunari
          - sensor.dark_sky_cloud_coverage
          - sensor.netatmo_regenmesser_rain
          - sensor.netatmo_regenmesser_sum_rain_1
          - sensor.netatmo_outdoor_temperature
          - sensor.netatmo_outdoor_humidity
          - sensor.dark_sky_apparent_temperature
          - sensor.dark_sky_wind_speed
          - type: divider
          - switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_4
          - switch.switch
          - switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch
      - type: entities
        title: Finestre
        show_header_toggle: true
        entities:
          - cover.level
          - cover.level_4
          - cover.level_2
          - cover.level_3
      - type: vertical-stack
        cards:
        - type: entities
          title: Power
          show_header_toggle: false
          entities:
            - entity: switch.switch_6 #Forno
            - switch.switch_7 # Lavastoviglie
            - switch.neo_coolcam_power_plug_12a_switch #cantina portavino
            - switch.switch_10 # Lavatrice
            - switch.switch_16 # iMac
        - type: entities
          title: Consumi
          show_header_toggle: true
          entities:
            - sensor.neo_coolcam_power_plug_12a_power
            - sensor.neo_coolcam_power_plug_12a_power_2
            - sensor.neo_coolcam_power_plug_12a_power_10
            - sensor.neo_coolcam_power_plug_12a_power_8
            - sensor.neo_coolcam_power_plug_12a_power_3
      - type: entities
        title: Sonos
        entities:
          - media_player.salotto
          - media_player.camere

  - title: meteo
    icon: mdi:umbrella-outline
    badges:
      - sensor.dark_sky_summary
    cards:
      - type: vertical-stack
        cards:
        - type: iframe
          url: https://embed.windy.com/embed2.html?lat=42.912&lon=10.525&zoom=8&level=surface&overlay=rain&menu=&message=&marker=&calendar=now&pressure=true&type=map&location=coordinates&detail=&detailLat=42.011&detailLon=10.522&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1
          aspect_ratio: 100%
        - type: weather-forecast
          entity: weather.meteo
        - type: thermostat
          entity: climate.termostatod

  - title: multimedia
    icon: mdi:movie
    cards:
      - type: horizontal-stack
        cards:
        - type: media-control
          entity: media_player.salotto
        - type: media-control
          entity: media_player.camere
      - type: horizontal-stack
        cards:
        - type: media-control
          entity: media_player.living
        - type: media-control
          entity: media_player.lg_tv_remote


  - title: automazioni
    icon: mdi:auto-fix
    cards:
      - type: horizontal-stack
        cards:
        - type: entity-button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.buongiorno
          entity: script.buongiorno
          name: GIORNO
          icon: mdi:alarm-check
        - type: entity-button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.buonanotte
          name: NOTTE
          entity: script.buonanotte
          icon: mdi:hotel
        - type: entity-button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.spengitv
          entity: script.spengitv
          name: TV OFF
          icon: mdi:television-classic-off
        - type: entity-button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.dolcedivano
          entity: script.dolcedivano
          icon: mdi:sofa
        - type: entity-button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.pioggia
          entity: script.pioggia
          icon: mdi:weather-pouring
      - type: entities
        title: Christmass Card
        show_header_toggle: false
        entities:
          - sensor.giornianatale
          - switch.christmas_light
          - entity: switch.sonoff_100009f6b1
            name: Albero di natale
            icon: mdi:android-auto
          - input_boolean.musica_natale
          - type: section
            label: Timer
          - group.automazioni_natale
          - input_datetime.accendi_natale
          - input_boolean.tramonto_natale
          - input_datetime.spengi_natale
      - type: entities
        title: Automazioni
        show_header_toggle: false
        entities:
          - automation.pioggia
          - automation.guardo_la_tv
          - automation.bagno_sera
          - automation.bagno_notte
          - automation.notifica_fine_lavaggio
          - script.sonosflow
      - type: entities
        title: Energy Saver
        show_header_toggle: false
        entities:
          - automation.camerina_out_day
          - automation.camerina_out
          - automation.camerina_out_out
          - automation.camerina_return
          - automation.philips_energy
      - type: entities
        title: Automazioni di Sistema
        show_header_toggle: false
        entities:
          - automation.start_homekit
          - automation.backup_automatico
          - automation.spazio_libero
          - automation.notifica_aggiornamento
          - automation.toner
          - type: divider
          - automation.test_notifica
          - automation.test_sonos


  - title: Utility
    icon: mdi:settings
    cards:
      - type: entities
        title: Utility
        show_header_toggle: false
        entities:
          - switch.wol_imac
          - sensor.iphone_battery_level
          - sensor.iphone_di_muriel_battery_level
          - sensor.ipad_di_muriel_battery_level
          - type: divider
          - sensor.neo_coolcam_battery_powered_pir_sensor_burglar
          - sensor.netatmo_outdoor_battery
          - sensor.netatmo_regenmesser_battery
          - sensor.netatmo_outdoor_radio
          - sensor.netatmo_regenmesser_radio
          - sensor.netatmo_indoor_wifi
          - sensor.samsung_m2020_series_1921681137_toner_black
          - sensor.sala_filter_life
      - type: entities
        title: Zwave
        show_header_toggle: false
        entities:
          - zwave.aeotec_zw090_zstick_gen5_eu
          - zwave.aeotec_zw117_range_extender_6
          - zwave.fibaro_system_fgd212_dimmer_2
          - zwave.fibaro_system_fgd212_dimmer_2_2
          - zwave.fibaro_system_fgrm222_roller_shutter_controller_2
          - zwave.fibaro_system_fgrm222_roller_shutter_controller_2_2
          - zwave.fibaro_system_fgrm222_roller_shutter_controller_2_3
          - zwave.fibaro_system_fgrm222_roller_shutter_controller_2_4
          - zwave.fibaro_system_fgs222_double_relay_switch_2x15kw
          - zwave.fibaro_system_fgs222_double_relay_switch_2x15kw_2
          - zwave.fibaro_system_fgs222_double_relay_switch_2x15kw_3
          - zwave.fibaro_system_fgs222_double_relay_switch_2x15kw_4
          - zwave.neo_coolcam_power_plug_12a
          - zwave.neo_coolcam_power_plug_12a_2
          - zwave.neo_coolcam_power_plug_12a_3
          - zwave.neo_coolcam_power_plug_12a_4
          - zwave.neo_coolcam_power_plug_12a_5
          - zwave.neo_coolcam_power_plug_12a_6
          - zwave.neo_coolcam_battery_powered_pir_sensor
      - type: vertical-stack
        cards:
        - type: entities
          title: Raspberry
          show_header_toggle: false
          entities:
            - sensor.cpu_temperature
            - sensor.processor_use
            - sensor.disk_use_percent_
            - sensor.memory_free
            - sensor.network_in_eth0
            - sensor.network_out_eth0
            - sensor.memory_use_percent
            - sensor.last_boot
        - type: history-graph
          entities:
            - sensor.cpu_temperature
            - sensor.processor_use
        - type: entities
          title: Connessione
          show_header_toggle: False
          entities:
          - sensor.ssl_certificate_expiry
          - sensor.pihole_ads_blocked_today
          - sensor.pihole_dns_queries_today
          - sensor.pihole_dns_unique_clients
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping

      - type: entities
        title: Sensore di Movimento
        show_header_toggle: true
        entities:
          - binary_sensor.sensor
          - sensor.neo_coolcam_battery_powered_pir_sensor_luminance
