
resources:
  - url: /local/slider-entity-row.js
    type: js
  - url: /local/lovelace/card-tools.js
    type: js
  - url: /local/lovelace/mini-graph-card-bundle.js  # https://github.com/kalkih/mini-graph-card
    type: js
  - url: /local/lovelace/card-modder.js
    type: js
  - url: /local/lovelace/fold-entity-row.js
    type: js

title: Dari's Home Assistant

views:
  - title: default_view  #pagina
    icon: mdi:home
    badges:
      - device_tracker.davides_iphone
      - device_tracker.iphone_di_muriel
    cards:               # card della pagina
      - type: horizontal-stack
        cards:
        - type: entity-button
          tap_action:
            action: toggle
          name: CANCELLO
          entity: switch.switch
        - type: entity-button
          tap_action:
            action: toggle
          name: PEDONALE
          entity: switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch
        - type: entity-button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.spengitv
          entity: script.spengitv
          name: TV OFF
          icon: mdi:power

      - type: entities
        title: Luci
        show_header_toggle: False
        entities:
          - type: section
            label: Piano Terra
          - switch.switch_9
          - switch.shellypensili
          - switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_2
          - switch.switch_8
          - switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_3
          - switch.switch_15
          - switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_6
          - type: divider
#          - switch.christmas_light
          - switch.switch_14
          - switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_4
          - type: section
            label: Piano Primo
          - type: custom:slider-entity-row
            entity: light.level
          - type: custom:slider-entity-row
            entity: light.level_2
          - type: custom:slider-entity-row
            entity: light.camera
          - type: custom:slider-entity-row
            entity: light.studio
      - type: entities
        title: Confort Living
        show_header_toggle: false
        entities:
          - climate.netatmo_piano_terra
          - fan.sala
          - type: divider
          - sensor.netatmo_indoor_temperature
          - sensor.netatmo_indoor_humidity
          - sensor.sala_humidity
          - sensor.netatmo_indoor_pressure
          - sensor.sala_aqi
          - sensor.netatmo_indoor_co2
          - sensor.sala_dust
          - sensor.netatmo_indoor_noise
      - type: picture-glance
        title: Living
        entities: #[]
          - sensor.netatmo_indoor_pressure
          - sensor.sala_aqi
          - sensor.netatmo_indoor_co2
          - sensor.sala_dust
          - sensor.netatmo_indoor_noise
        camera_image:  camera.camliving

      - type: entities
        title: Giardino
        show_header_toggle: false
        entities:
          - sun.sun
          - sensor.fasilunari
          - sensor.dark_sky_cloud_coverage
          - sensor.netatmo_regenmesser_rain
          - sensor.netatmo_regenmesser_sum_rain_1
          - sensor.smartweather_rain_today
          - sensor.netatmo_outdoor_temperature
          - sensor.netatmo_outdoor_humidity
          - sensor.dark_sky_apparent_temperature
          - sensor.dark_sky_wind_speed
          - type: divider
          - switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_4
          - switch.switch
          - switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch
      - type: entities
        title: Finestre
        show_header_toggle: false
        entities:
          - cover.level
          - cover.level_4
          - cover.level_2
          - cover.level_3

      - type: entities
        title: Sonos
        entities:
          - media_player.salotto
          - media_player.camere
############################################################################
  - title: Power
    icon: mdi:chart-line-stacked
    badges:
      - sensor.widom_ume304_energy_driven_switch_power
      - sensor.widom_ume304_energy_driven_switch_energy
    cards:
      - type: vertical-stack
        cards:

        - type: entities
          title: Consumi
          show_header_toggle: false
          entities:
            - automation.controllocarichi
            - sensor.neo_coolcam_power_plug_12a_power
            - sensor.neo_coolcam_power_plug_12a_power_2
            - sensor.neo_coolcam_power_plug_12a_power_10
            - sensor.neo_coolcam_power_plug_12a_power_8
            - sensor.neo_coolcam_power_plug_12a_power_11
            - sensor.neo_coolcam_power_plug_12a_power_3
            - type: divider
            - sensor.widom_ume304_energy_driven_switch_power
        - type: custom:mini-graph-card
          entities:
            - entity: sensor.widom_ume304_energy_driven_switch_power
          name: Consumo Energetico
          show:
            graph: bar
        - type: entities
          title: Power
          show_header_toggle: false
          entities:
            - entity: switch.switch_6 #Forno
            - switch.switch_7 # Lavastoviglie
            - switch.neo_coolcam_power_plug_12a_switch #cantina portavino
            - switch.switch_10 # iMac
            - switch.neo_coolcam_power_plug_12a_switch_2 #Asciugatrice
            - switch.switch_16 # Lavatrice

      - type: vertical-stack
        cards:
        - type: markdown
          content: >
            ## Consumi e costi

        - type: custom:fold-entity-row
          head:
            type: section
            label: Impostazioni Consumi
          items:
            - entity: input_datetime.f1_ora_inizio
              name: Orario Fascia 1
            - entity: input_number.costo_f1
              name: Costo KWh Fascia 1
            - entity: input_datetime.f2_ora_inizio
              name: Orario Fascia 2
            - entity: input_number.costo_f2
              name: Costo KWh Fascia 2
            - entity: input_boolean.tariffa_weekend
              name: Attiva F2 e Tariffa Week end

        - type: entities
          title: Consumi e costi oggi
          show_header_toggle: false
          entities:
          - entity: sensor.consumo_giornaliero_f1
            name: Consumo Fascia 1
          - entity: sensor.costo_consumo_oggi_f1
            name: Costo Fascia 1
          - entity: sensor.consumo_giornaliero_f2
            name: Consumo Fascia 2
          - entity: sensor.costo_consumo_oggi_f2
            name: Costo Fascia 2
          - entity: sensor.consumo_totale_oggi
            name: Consumo Totale
          - entity: sensor.costo_consumo_oggi_totale
            name: Costo Totale
        - type: entities
          title: Consumi e costi mensile
          show_header_toggle: false
          entities:
          - entity: sensor.consumo_mensile_f1
            name: Consumo Fascia 1
          - entity: sensor.costo_consumo_mensile_f1
            name: Costo Fascia 1
          - entity: sensor.consumo_mensile_f2
            name: Consumo Fascia 2
          - entity: sensor.costo_consumo_mensile_f2
            name: Costo Fascia 2
          - entity: sensor.consumo_totale_mensile
            name: Consumo Totale
          - entity: sensor.costo_consumo_mensile_totale
            name: Costo Totale
#################
  - title: automazioni
    icon: mdi:auto-fix
    cards:
      - type: horizontal-stack
        cards:
        - type: entity-button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.buongiorno
          entity: script.buongiorno
          name: GIORNO
          icon: mdi:alarm-check
        - type: entity-button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.buonanotte
          name: NOTTE
          entity: script.buonanotte
          icon: mdi:hotel
        - type: entity-button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.spengitv
          entity: script.spengitv
          name: TV OFF
          icon: mdi:television-classic-off
        - type: entity-button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.dolcedivano
          entity: script.dolcedivano
          icon: mdi:sofa
        - type: entity-button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id: script.pioggia
          entity: script.pioggia
          icon: mdi:weather-pouring

      - type: vertical-stack
        cards:
        - type: plant-status
          name: Chamadorea
          entity: plant.chamadorea
        - type: custom:fold-entity-row
          head:
            type: section
            label: Impostazioni Timer Terrario
          items:
            - entity: group.automazioni_pack_switch
            - entity: input_datetime.accendi_switch
            - entity: input_boolean.tramonto_switch
            - entity: input_datetime.spengi_switch
        - type: entities
          title: Terrario
          show_header_toggle: false
          entities:
            - entity: switch.switch1
              name: Luce Terrario
              icon: mdi:tortoise
      - type: entities
        title: Automazioni
        show_header_toggle: false
        entities:
          - automation.pioggia
          - group.lavatrice
          - group.asciugatrice
          - automation.arrivabetty
          - script.sonosflow
      - type: entities
        title: Automazioni Luci
        show_header_toggle: false
        entities:
          - automation.guardo_la_tv
          - automation.camerina_out_day
          - automation.camerina_out
          - automation.camerina_out_out
          - automation.camerina_return
          - automation.philips_energy
          - automation.bagno_pir
          - automation.bagno_sera
          - automation.bagno_notte
          - automation.bagno_energy
          - automation.risparmio_energetico_giorno
          - automation.assente
      - type: entities
        title: Automazioni di Sistema
        show_header_toggle: false
        entities:
#          - automation.start_homekit
          - automation.controllocarichi
          - automation.backup_automatico
          - automation.spazio_libero
          - automation.notifica_aggiornamento
          - automation.toner
          - automation.start_homekit
          - type: divider
          - automation.test_notifica
          - automation.test_sonos
#########################################################################

  - title: meteo
    icon: mdi:umbrella-outline
    badges:
      - sensor.dark_sky_summary
    cards:
      - type: vertical-stack
        cards:
        - type: iframe
          url: https://embed.windy.com/embed2.html?lat=42.912&lon=10.525&zoom=8&level=surface&overlay=rain&menu=&message=&marker=&calendar=now&pressure=true&type=map&location=coordinates&detail=&detailLat=42.011&detailLon=10.522&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1
          aspect_ratio: 100%
        - type: weather-forecast
          entity: weather.meteo
        - type: thermostat
          entity: climate.netatmo_piano_terra

  - title: multimedia
    icon: mdi:movie
    cards:
      - type: horizontal-stack
        cards:
        - type: media-control
          entity: media_player.salotto
        - type: media-control
          entity: media_player.camere
      - type: horizontal-stack
        cards:
        - type: media-control
          entity: media_player.living
        - type: media-control
          entity: media_player.lg_tv_remote
########################################################

  - !include lovelace/garden.yaml


#########################################################
  - title: Utility
    icon: mdi:settings
    cards:
      - type: entities
        title: Utility
        show_header_toggle: false
        entities:
          - switch.wol_imac
          - sensor.iphone_battery_level
          - sensor.iphone_di_muriel_battery_level
          - sensor.ipad_di_muriel_battery_level
          - type: divider
          - sensor.netatmo_outdoor_battery
          - sensor.netatmo_regenmesser_battery
          - sensor.netatmo_outdoor_radio
          - sensor.netatmo_regenmesser_radio
          - sensor.netatmo_indoor_wifi
          - sensor.samsung_m2020_series_1921681137_toner_black
          - sensor.sala_filter_life
          - sensor.last_boot
      - type: entities
        title: Zwave
        show_header_toggle: false
        entities:
          - zwave.aeotec_zw090_zstick_gen5_eu
          - zwave.aeotec_zw117_range_extender_6
          - zwave.fibaro_system_fgd212_dimmer_2
          - zwave.fibaro_system_fgd212_dimmer_2_2
          - zwave.fibaro_system_fgrm222_roller_shutter_controller_2
          - zwave.fibaro_system_fgrm222_roller_shutter_controller_2_2
          - zwave.fibaro_system_fgrm222_roller_shutter_controller_2_3
          - zwave.fibaro_system_fgrm222_roller_shutter_controller_2_4
          - zwave.fibaro_system_fgs222_double_relay_switch_2x15kw
          - zwave.fibaro_system_fgs222_double_relay_switch_2x15kw_2
          - zwave.fibaro_system_fgs222_double_relay_switch_2x15kw_3
          - zwave.fibaro_system_fgs222_double_relay_switch_2x15kw_4
          - zwave.fibaro_system_fgs222_double_relay_switch_2x15kw_6
          - zwave.fibaro_system_fgs222_double_relay_switch_2x15kw_7
          - zwave.neo_coolcam_power_plug_12a
          - zwave.neo_coolcam_power_plug_12a_2
          - zwave.neo_coolcam_power_plug_12a_3
          - zwave.neo_coolcam_power_plug_12a_4
          - zwave.neo_coolcam_power_plug_12a_5
          - zwave.neo_coolcam_power_plug_12a_6
          - zwave.unknown_node_30
          - zwave.neo_coolcam_battery_powered_pir_sensor
          - zwave.fibaro_system_fgms001zw5_motion_sensor
          - zwave.widom_ume304_energy_driven_switch

      - type: vertical-stack
        cards:
        - type: glance
          title: NUC System Monitor
          entities:
            - entity: sensor.processor_use
              name: CPU Load
            - entity: sensor.disk_use_percent
              name: Disco
            - entity: sensor.memory_use_percent
              name: Ram
            - entity: sensor.last_boot
        - type: custom:mini-graph-card
          entities:
            - sensor.processor_use
        - type: entities
          title: Connessione
          show_header_toggle: False
          entities:
          - sensor.ssl_certificate_expiry
          - sensor.pi_hole_ads_blocked_today
          - sensor.pi_hole_dns_queries_today
          - sensor.pi_hole_dns_unique_clients
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping

      - type: entities
        title: Sensore di Movimento
        show_header_toggle: False
        entities:
          - binary_sensor.sensor
          - sensor.neo_coolcam_battery_powered_pir_sensor_luminance
          - type: divider
          - binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor
          - sensor.fibaro_system_fgms001zw5_motion_sensor_luminance
          - sensor.fibaro_system_fgms001zw5_motion_sensor_seismic_intensity
          - sensor.fibaro_system_fgms001zw5_motion_sensor_burglar
          - sensor.fibaro_system_fgms001zw5_motion_sensor_temperature
