#============================================================================
#=== Not that I don't trust my programming but...
#===   1. Disattivare valvole e programmi quando l'interruttore di controllo principale è disattivato
#===   2. Spegnere tutte le valvole quando HA si avvia
#===   3. Non consentire più di una valvola alla volta
#===   4. Disattiva le valvole da se una di queste è attiva per più di 30 minuti
#===
#=== Better safe than sorry!
#============================================================================

#================
#=== Automations
#================
automation:

  #====================================================================
  #=== Master Control Switch
  #=== Turn off valves and schedules when master control switch is off
  #====================================================================
  - alias: Irrigation Failsafe - master control switch
    initial_state: on
    trigger:
    - platform: state
      entity_id: input_boolean.irrigation_master_control_switch
      to: 'off'

    - platform: homeassistant
      event: start

    action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.cycle1_enable
        - input_boolean.cycle2_enable
        - input_boolean.cycle1_manual_run
        - input_boolean.cycle2_manual_run
        - switch.zone1_valve
        - switch.zone2_valve


  #=======================================
  #=== Home Assistant starts
  #=== Turn off all valves when HA starts
  #=======================================
  - alias: Irrigation Failsafe - HA start
    initial_state: on
    trigger:
    - platform: homeassistant
      event: start

    action:
    - service: homeassistant.turn_off
      entity_id:
        - switch.zone1_valve
        - switch.zone2_valve

  #==================================================================
  #=== Don't allow more than one valve on at one time.
  #=== And
  #=== Turn off valve 1 to 4 if it is on for longer than 30 minutes.
  #=== Turn off valve 5 if it is on for longer than 59 minutes.
  #==================================================================
  #=== Valve 1 ON
  - alias: Irrigation Failsafe - Valve 1 on
    initial_state: on
    trigger:
    - platform: state
      entity_id:
      - switch.zone1_valve
      to: 'on'

    action:
    - service: homeassistant.turn_off
      entity_id:
        - switch.zone2_valve

    - wait_template: "{{ is_state('switch.zone1_valve', 'off') }}"
      timeout: '00:30:15'

    - service: homeassistant.turn_off
      entity_id: switch.zone1_valve


  #=== Valve 2 ON
  - alias: Irrigation Failsafe - Valve 2 on
    initial_state: on
    trigger:
    - platform: state
      entity_id:
      - switch.zone2_valve
      to: 'on'

    action:
    - service: homeassistant.turn_off
      entity_id:
        - switch.zone1_valve

    - wait_template: "{{ is_state('switch.zone2_valve', 'off') }}"
      timeout: '00:30:15'

    - service: homeassistant.turn_off
      entity_id: switch.zone2_valve
