#=================
# === Automations
#=================
automation:

  #====================================================================
  #=== Interruttore di controllo principale
  #===
  #=== Questo Accende o spegne:
  #===   Tutte le automazioni per l'irrigazione.
  #===   Tutte le automazioni relative al Meteo utilizzate in Irrigazione.
  #===
  #===   Ad esempio tutte le automazioni con un nome che inizia con entrambi
  #===        'Irrigation - ' or
  #===        'Weather Irrigation - '
  #===
  #=== Controllando anche quando HA si avvia.
  #====================================================================
  - alias: Irrigation Master Control Switch
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.irrigation_master_control_switch

      - platform: homeassistant
        event: start

    action:
      #=== Turn all Irrigation automations on or off
      - service_template: >
          {% if is_state('input_boolean.irrigation_master_control_switch', 'on') %}
            automation.turn_on
          {% else %}
            automation.turn_off
          {% endif %}
        data_template:
          entity_id: >
            {% for item in states['automation'] if item.name.startswith('Irrigation - ') -%}
              {% if not loop.first %},{% endif %}{{ item.entity_id }}
            {%- endfor %}

      #=== Turn all Weather Irrigation automations on or off
      - service_template: >
          {% if is_state('input_boolean.irrigation_master_control_switch', 'on') %}
            automation.turn_on
          {% else %}
            automation.turn_off
          {% endif %}
        data_template:
          entity_id: >
            {% for item in states['automation'] if item.name.startswith('Irrigation Weather - ') -%}
              {% if not loop.first %},{% endif %}{{ item.entity_id }}
            {%- endfor %}

      #=== Stop both cycles
      - service: input_boolean.turn_off
        data:
          entity_id:
            - input_boolean.cycle1_manual_run
            - input_boolean.cycle2_manual_run
